language: php

php:
- 7.1
- 7.2

sudo: false

services:
  - redis-server

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.bin

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit --verbose $PHPUNIT_FLAGS
